# Common configuration shared between all applications
configserver:
  name: Docker JHipster Registry
  status: Connected to the JHipster Registry running in Docker

jhipster:
  security:
    authentication:
      jwt:
        # secret key which should be base64 encoded and changed in production
        base64-secret: YTk4NDAwM2Y3Zjc5OGNkNDQyM2JlYjUwMTY2NTNjOGYzZGQwMjRkMTFhZjE4MTc0ZmExMTlkNmM0YWVlYTE3ZTQ1MDQ4ZjE4ZTQxNjMxYTgwODUyYmM3NjM0MmVhNzBhMmI5MDUwZGVmMzRjZDAwZDI3NjViOWZhN2UwMjRmMzc=

eureka:
  client:
    service-url:
      defaultZone: http://admin:${jhipster.registry.password}@jhipster-registry:8761/eureka/
